export enum FamilyRelation {
    Father = 'father',
    Mother = 'mother',
    Son = 'son',
    Daughter = 'daughter',
    Brother = 'brother',
    Sister = 'sister',
    Grandfather = 'grandfather',
    Grandmother = 'grandmother',
    Grandson = 'grandson',
    Granddaughter = 'granddaughter',
    Uncle = 'uncle',
    Aunt = 'aunt',
    Nephew = 'nephew',
    Niece = 'niece',
    Cousin = 'cousin',
    Stepfather = 'stepfather',
    Stepmother = 'stepmother',
    Stepson = 'stepson',
    Stepdaughter = 'stepdaughter',
    HalfBrother = 'half brother',
    HalfSister = 'half sister',
    Godfather = 'godfather',
    Godmother = 'godmother',
    Godson = 'godson',
    Goddaughter = 'goddaughter',
    FatherInLaw = 'father-in-law',
    MotherInLaw = 'mother-in-law',
    SonInLaw = 'son-in-law',
    DaughterInLaw = 'daughter-in-law',
    BrotherInLaw = 'brother-in-law',
    SisterInLaw = 'sister-in-law',
  }
  